--drops tables, for testing purposes
DROP TABLE PROFESSOR CASCADE;
DROP TABLE GRADUATESTUDENT CASCADE;
DROP TABLE DEPARTMENT CASCADE;
DROP TABLE PROJECT CASCADE;
DROP TABLE COINVESTIGATOR CASCADE;
DROP TABLE RESEARCHASSISTANT CASCADE;
